In [15]:
#This code snippet is importing the NumPy library as np and creating two NumPy arrays, v and w. 
import numpy as np
v = np.array([1,-1,2])
w = np.array([2,5,2])

In [16]:
#sum
print(v+w)

[3 4 4]


In [17]:
#diff
print(v-w)

[-1 -6  0]


In [18]:
#scaler multiplication
print(3*v)
print(3*w)

[ 3 -3  6]
[ 6 15  6]


In [19]:
#This code snippet is calculating the Euclidean norm (also known as the magnitude or length) of two vectors `v` and `w` using NumPy
print(np.linalg.norm(v))
print(np.linalg.norm(w))

2.449489742783178
5.744562646538029


In [20]:
#This line of code is calculating the dot product of two arrays `v` and `w` using the `np.dot()` function from the NumPy library.
s= np.dot(v,w);
print (s)

1
