In [32]:
#`import numpy as np` is a Python statement that imports the NumPy library and assigns it an alias `np`. This allows you to use functions and objects from the NumPy library by prefixing them with `np`.
import numpy as np

In [33]:
p = np.array([[1,7],[2,1],[3,2]])
print(p)

[[1 7]
 [2 1]
 [3 2]]


In [34]:
q = np.array([[1,1],[1,-1],[1,0]])
print(q)

[[ 1  1]
 [ 1 -1]
 [ 1  0]]


In [35]:
c1 = np.add(p,q)
print(c1)

[[2 8]
 [3 0]
 [4 2]]


In [36]:
c2 = np.subtract(p,q)
print(c2)

[[0 6]
 [1 2]
 [2 2]]


In [37]:
r = np.array([[1,3,1],[1,0,1]])
print(r)

[[1 3 1]
 [1 0 1]]


In [38]:
c3 = np.dot(p,r)
print(c3)

[[8 3 8]
 [3 6 3]
 [5 9 5]]


In [39]:
det = np.linalg.det(c3)
print(det)

0.0


In [40]:
s2 = np.linalg.inv(c3)
# LinAlgError                               Traceback (most recent call last)
# Cell In[20], line 1
# ----> 1 s2 = np.linalg.inv(c3)

# File c:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\linalg\_linalg.py:609, in inv(a)
#     606 signature = 'D->D' if isComplexType(t) else 'd->d'
#     607 with errstate(call=_raise_linalgerror_singular, invalid='call',
#     608               over='ignore', divide='ignore', under='ignore'):
# --> 609     ainv = _umath_linalg.inv(a, signature=signature)
#     610 return wrap(ainv.astype(result_t, copy=False))

# File c:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\linalg\_linalg.py:104, in _raise_linalgerror_singular(err, flag)
#     103 def _raise_linalgerror_singular(err, flag):
# --> 104     raise LinAlgError("Singular matrix")

# LinAlgError: Singular matrix

LinAlgError: Singular matrix

In [ ]:
m = np.array([[1,-1],[2,3]])
print(np.linalg.inv(m))

[[ 0.6  0.2]
 [-0.4  0.2]]
